# Generated by Django 4.2.5 on 2023-09-26 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PollQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('question_value', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.polloptions')),
                ('ques_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pollquestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='polloptions',
            name='ques_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pollquestions'),
        ),
    ]
