# Generated by Django 4.0.7 on 2023-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollquestions',
            old_name='question_value',
            new_name='ques_value',
        ),
        migrations.AlterField(
            model_name='pollquestions',
            name='status',
            field=models.BooleanField(default=1, max_length=100),
        ),
    ]
