# Generated by Django 4.0.7 on 2023-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_question_value_pollquestions_ques_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestions',
            name='ques_value',
            field=models.CharField(max_length=1000),
        ),
    ]
